### ISSUE TITLE
Report Issue Email form should be callback instead of page-refresh

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/DeveloperPortalDocs#1]
Currently when one clicks report an issue (bottom of docs pages), and fill the form, then click on “Submit” - the page refreshes and not message is shown to the user that the email was sent successfully.
It should be changed to a callback in JS instead, and instead of page-refresh, the form should show a thank you message.

**Comment by jessp01** [comment]
Done.  However, you might want to move or change the size of the post_message div. Does not look righ tto me.
