### ISSUE TITLE
The RSS feed and Sitemap are not showing proper links

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/DeveloperPortalDocs#10]
Both the [RSS feed](https://vpaas.kaltura.com/feed.xml) and the [Sitemap](https://vpaas.kaltura.com/sitemap.xml) should show only public-facing site pages.
That means, site pages such as homepage, register, and kaltura-start page. And /documentation/* pages.
It should never show pages that are conditional (such as thank-you or success pages) nor show assets (such as css files) nor show configuration files (such as [resources.md](https://vpaas.kaltura.com/resources/) nor [search](https://vpaas.kaltura.com/search)).

Thanks

**Comment by jessp01** [comment]
Done. Any page that should not appear in the XMLs, should have:
sitemap: false
as part of it's front matter. For instance:
https://raw.githubusercontent.com/kaltura/DeveloperPortalDocs/master/404.md

**Comment by zoharbabin** [comment]
Wonderful, thanks.
