### ISSUE TITLE
Registration page fails to submit

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/DeveloperPortalDocs#3]
Fill all the fields, choose the "VPaaS Account", click submit... nothing happens.

The Console shows the following errors:
```json
Object {type: "VALIDATION", message: "Some payment method input fields are invalid.", details: Object}
```

![errors](https://cloud.githubusercontent.com/assets/150514/14426090/ef8a6774-fff4-11e5-8955-046df47d9527.png)

**Comment by KalturaCommunity** [comment]
Yes, this comes from the Stripe code. Even when hiding the div, the 
validation is still attempted. It can be solved, of course but seeing how 
we'll go w/o payments in the beginning anyhow, I'll just remove this JS 
and div for now.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by jessp01** [comment]
Done.
