### ISSUE TITLE
Resizing the window on doc pages makes the side-menu disapear

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/DeveloperPortalDocs#4]
On mac, chrome (latest).
Start the browser on the widest resolution.
Visit: https://vpaas.kaltura.com/documentation/media-management/introduction-to-content-preparation-and-transcoding
Resize the browser window till you get the mobile menu.
click on the mobile menu to open, and click again to close it.
Then resize the browser window back to full size.
The side-menu is gone.

**Comment by devinllp** [comment]
This issue doesn't show up on a device on load, it's only when you resize down and up again which is not really something that people do. Do you want me to still look at this?

**Comment by zoharbabin** [comment]
nah
