### ISSUE TITLE
Add anchors to h2, h3, h4, and h5 headers automatically

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/DeveloperPortalDocs#6]
In docs pages, h elements should have name and id added automatically to them as part of the markdown rendering.
This will allow us to deep-link to headers. See how GitHub README works (headers automatically turn into links).

This could be a good solution for it:
https://github.com/renettarenula/anchorific.js

**Comment by jessp01** [comment]
Done. There was really not need for anything other than a simple JS code in _layout/page.html:
```
<script>
$('h2,h3,h4,h5,h6').filter('[id]').each(function () {
    $(this).html('<a href="#'+$(this).attr('id')+'">' + $(this).text() + '</a>');
});
</script>
```
