### ISSUE TITLE
Enable gzip compression and js/css combining and minifing on Apache

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/DeveloperPortalDocs#9]
let's improve load time

![audit-vpaas](https://cloud.githubusercontent.com/assets/150514/14743496/72d56b0c-08aa-11e6-8b17-f79aab7c3496.png)

**Comment by jessp01** [comment]
We already do use Apache's mod deflate for that. In fact, it is the default when installing Apache over Debian/Ubuntu and most other dists.

i.e:
```
<IfModule mod_deflate.c>
        <IfModule mod_filter.c>
                # these are known to be safe with MSIE 6
                AddOutputFilterByType DEFLATE text/html text/plain text/xml

                # everything else may cause problems with MSIE 6
                AddOutputFilterByType DEFLATE text/css
                AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
                AddOutputFilterByType DEFLATE application/rss+xml
                AddOutputFilterByType DEFLATE application/xml
        </IfModule>
</IfModule>
```

If you expend the "Enable gzip compression" in your "Audits" tab you will see:
Enable gzip compression (2)
Compressing the following resources with gzip could reduce their transfer size by about two thirds (~1.5 KB):
getAllAppDefault.esi
could save ~132 B
getSegment.php
could save ~1.4 KB

And these are external resources taken from:
http://wd-edge.sharethis.com/button/getAllAppDefault.esi?cb=stLight.allDefault&app=all&publisher=7acb66da-36ad-4c46-ba0d-f7ede13aa36c&domain=localhost
http://seg.sharethis.com/getSegment.php?purl=http%3A%2F%2Flocalhost%3A8888%2Fdocumentation%2Fcontribute%2FArticle-Style-Structure-Guidelines%23sthash.auBQgegf.IFnZvBcb.dpbs&jsref=http%3A%2F%2Flocalhost%3A8888%2Fdocumentation%2Fmedia-management%2Fplaylist-management.html&rnd=1461374894596

so, nothing for me to do here.
